<a href="https://colab.research.google.com/github/simranwork/Model_training/blob/master/House_prediction_model/house_price_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
house = pd.read_csv('House_Data (2).csv')
house.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
house.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
for column in house.columns:
  print(house[column].value_counts())
  print('#'*20)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
####################
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64
####################
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64
####################
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64
####################
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: society, Length: 2688, dtype: int64
####################
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: total_sqft, Length: 2116, dtype: int64
####################
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64
####################
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64
####################
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: price, Length: 1994, dtype: int64
####################

In [ ]:
#dropping columns with no us or max null values
house = house.drop(columns=['area_type','society','balcony','availability'])
house.sample(5)

                       location   size total_sqft  bath  price
12598            Sarjapur  Road  3 BHK       1347   2.0  44.00
2961          Somasundara Palya  3 BHK       1570   3.0  68.00
6725                Tumkur Road  2 BHK       1027   2.0  60.00
12910  Electronic City Phase II  2 BHK       1200   2.0  34.65
11640                   Varthur  3 BHK       1560   3.0  90.00

In [ ]:
house.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
#-->
# avg 2 bathroom,112 lakh price
# probably error in max number of bathroom and max 36 crore house price
# min 1 bathroom and 8 lakh house

In [ ]:
house.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [ ]:
house[house['location'].isnull()]

    location   size total_sqft  bath  price
568      NaN  3 BHK       1600   3.0   86.0

In [ ]:
a = house[house['price']>80.0]

In [ ]:
a['location'].mode()

0    Whitefield
Name: location, dtype: object

In [ ]:
# since in that price range whitefield is mostly there we will replace the null value with Whitefield

In [ ]:
house['location']=house['location'].fillna('Whitefield')

In [ ]:
house[house['location'].isnull()]

Empty DataFrame
Columns: [location, size, total_sqft, bath, price]
Index: []

In [ ]:
house[house['size'].isnull()]

             location size   total_sqft  bath    price
579    Sarjapur  Road  NaN  1200 - 2400   NaN   34.185
1775         IVC Road  NaN  2000 - 5634   NaN  124.000
2264     Banashankari  NaN         2400   NaN  460.000
2809   Sarjapur  Road  NaN  1200 - 2400   NaN   28.785
2862      Devanahalli  NaN  1500 - 2400   NaN   46.800
5333      Devanahalli  NaN  2100 - 5405   NaN  177.115
6423       Whitefield  NaN         2324   NaN   26.730
6636           Jigani  NaN         1500   NaN   25.490
6719          Hoskote  NaN   800 - 2660   NaN   28.545
7680     Kasavanhalli  NaN         5000   NaN  400.000
8306           Anekal  NaN         1453   NaN   16.500
8565       Carmelaram  NaN         2000   NaN  120.000
8703      Mysore Road  NaN  1200 - 2400   NaN   42.300
10634      Rajankunte  NaN         1575   NaN   31.110
11019       Yelahanka  NaN  1200 - 1800   NaN   12.750
11569      Hosur Road  NaN         1350   NaN    8.440

In [ ]:
house['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [ ]:
#we can fill missing values of size using squarefeet area col but since there are only 16 such rows we'll direct fill it with the max value that is 2 BHK

In [ ]:

house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
house['size']=house['size'].fillna('2 BHK')

In [ ]:
house[house['bath'].isnull()]

             location       size   total_sqft  bath    price
56        Devanahalli  4 Bedroom  3010 - 3410   NaN  192.000
81        Hennur Road  4 Bedroom  2957 - 3450   NaN  224.500
224       Devanahalli      3 BHK  1520 - 1740   NaN   74.820
344    Kanakpura Road      1 BHK          525   NaN   21.530
579    Sarjapur  Road      2 BHK  1200 - 2400   NaN   34.185
...               ...        ...          ...   ...      ...
11496  Kanakpura Road      1 BHK          525   NaN   27.000
11569      Hosur Road      2 BHK         1350   NaN    8.440
12768    Bettahalsoor  5 Bedroom         3210   NaN  353.000
12861        KR Puram      4 BHK  2204 - 2362   NaN  121.000
13240     Devanahalli      1 BHK  1020 - 1130   NaN   52.570

[73 rows x 5 columns]

In [ ]:
house['bath'].median()

2.0

In [ ]:
house['bath']=house['bath'].fillna(2)

In [ ]:
house.describe()

               bath         price
count  13320.000000  13320.000000
mean       2.688814    112.565627
std        1.338754    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
# >8 --1 bath
# >72--2 bath
# >120--3 bath

In [ ]:
house.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [ ]:
#convert size as int
house['bhk']=house['size'].str.split().str[0]

In [ ]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
 5   bhk         13320 non-null  object
dtypes: float64(2), object(4)
memory usage: 624.5+ KB

In [ ]:
house['bhk']=house['bhk'].astype('int')

In [ ]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
 5   bhk         13320 non-null  int64
dtypes: float64(2), int64(1), object(3)
memory usage: 624.5+ KB

In [ ]:
house=house.drop(columns=['size'])

In [ ]:
#convert range of total_sqft to avg of range
def range(x):
  temp = x.split('-')
  temp1= x.split('*')
  if len(temp)==2:
    return (float(temp[0])+float(temp[1]))/2
  if len(temp1)==2:
    return float(temp1[0])*float(temp1[1])
  try:
    return float(x)
  except:
    None

In [ ]:
house['total_sqft']=house['total_sqft'].apply(range)
house.head()

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

In [ ]:
#price per sq feet -- price/sq feet

In [ ]:
x=house['price']*100000/house['total_sqft']
house['price_per_sqfeet']=round(x,2)
house.head()

                   location  total_sqft  bath   price  bhk  price_per_sqfeet
0  Electronic City Phase II      1056.0   2.0   39.07    2           3699.81
1          Chikka Tirupathi      2600.0   5.0  120.00    4           4615.38
2               Uttarahalli      1440.0   2.0   62.00    3           4305.56
3        Lingadheeranahalli      1521.0   3.0   95.00    3           6245.89
4                  Kothanur      1200.0   2.0   51.00    2           4250.00

In [ ]:
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet
count,13320.000000,13320.000000,13320.000000,13320.000000,1.332000e+04
mean,1706.189908,2.688814,112.565627,2.802778,8.093629e+03
std,8491.994713,1.338754,148.971674,1.294496,1.078473e+05
min,1.000000,1.000000,8.000000,1.000000,3.061000e+01
25%,1100.000000,2.000000,50.000000,2.000000,4.262950e+03
50%,1277.000000,2.000000,72.000000,3.000000,5.431470e+03
75%,1680.000000,3.000000,120.000000,3.000000,7.313873e+03
max,653400.000000,40.000000,3600.000000,43.000000,1.200000e+07

In [ ]:
#in location let's keep the locations that occur frequently as it is and the ones that occur just one two times as other
house['location']=house['location'].apply(lambda x: x.strip())

In [ ]:
location_count = house['location'].value_counts()

In [ ]:
location_count_less_than_10=location_count[location_count<=10]

In [ ]:

location_count_less_than_10

Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: location, Length: 1053, dtype: int64

In [ ]:
house['location']=house['location'].apply(lambda x: 'other' if x in location_count_less_than_10 else x)

In [ ]:
house['location']

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316                       other
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13320, dtype: object

In [ ]:
#outlier detection and removal

In [ ]:
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet
count,13320.000000,13320.000000,13320.000000,13320.000000,1.332000e+04
mean,1706.189908,2.688814,112.565627,2.802778,8.093629e+03
std,8491.994713,1.338754,148.971674,1.294496,1.078473e+05
min,1.000000,1.000000,8.000000,1.000000,3.061000e+01
25%,1100.000000,2.000000,50.000000,2.000000,4.262950e+03
50%,1277.000000,2.000000,72.000000,3.000000,5.431470e+03
75%,1680.000000,3.000000,120.000000,3.000000,7.313873e+03
max,653400.000000,40.000000,3600.000000,43.000000,1.200000e+07

In [ ]:
#1 sqft house is not possible therefore that is an outlier
house['sqft_per_bhk']=house['total_sqft']/house['bhk']
house.head()

,location,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
0,Electronic City Phase II,1056.0,2.0,39.07,2,3699.81,528.0
1,Chikka Tirupathi,2600.0,5.0,120.00,4,4615.38,650.0
2,Uttarahalli,1440.0,2.0,62.00,3,4305.56,480.0
3,Lingadheeranahalli,1521.0,3.0,95.00,3,6245.89,507.0
4,Kothanur,1200.0,2.0,51.00,2,4250.00,600.0

In [ ]:
house['sqft_per_bhk'].describe()

count     13320.000000
mean        622.965403
std        2399.320516
min           0.250000
25%         473.333333
50%         552.500000
75%         625.000000
max      217800.000000
Name: sqft_per_bhk, dtype: float64

In [ ]:
house =house[house['sqft_per_bhk']>=300]
house.shape

(12569, 7)

In [ ]:
house['sqft_per_bhk'].describe()

count     12569.000000
mean        648.737505
std        2467.537874
min         300.000000
25%         492.000000
50%         562.666667
75%         631.000000
max      217800.000000
Name: sqft_per_bhk, dtype: float64

In [ ]:
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
count,12569.000000,12569.000000,12569.000000,12569.000000,12569.000000,12569.000000
mean,1750.298334,2.560108,111.432160,2.651205,6296.921037,648.737505
std,8739.354306,1.079761,151.926602,0.979617,4161.884291,2467.537874
min,300.000000,1.000000,8.440000,1.000000,30.610000,300.000000
25%,1116.000000,2.000000,49.000000,2.000000,4205.610000,492.000000
50%,1300.000000,2.000000,70.000000,3.000000,5291.830000,562.666667
75%,1703.000000,3.000000,115.000000,3.000000,6916.670000,631.000000
max,653400.000000,16.000000,3600.000000,16.000000,176470.590000,217800.000000

In [ ]:
house =house[house['price_per_sqfeet']<=10457]
house.shape

(11435, 7)

In [ ]:
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
count,11435.000000,11435.000000,11435.000000,11435.000000,11435.000000,11435.000000
mean,1688.123270,2.458417,84.195175,2.567293,5347.733160,645.104808
std,9147.206274,0.982040,67.446510,0.910599,1688.832787,2584.595481
min,300.000000,1.000000,8.440000,1.000000,30.610000,300.000000
25%,1100.000000,2.000000,47.000000,2.000000,4105.260000,495.416667
50%,1277.000000,2.000000,65.000000,2.000000,5081.300000,560.000000
75%,1636.500000,3.000000,97.715000,3.000000,6355.930000,625.000000
max,653400.000000,16.000000,2100.000000,16.000000,10451.660000,217800.000000

In [ ]:
house['bhk'].value_counts()

2     5361
3     4369
4      842
1      607
5      126
6       62
7       29
8       21
9       11
10       3
11       2
16       1
13       1
Name: bhk, dtype: int64

In [ ]:
house =house[house['bhk']<9]
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
count,11417.000000,11417.000000,11417.000000,11417.000000,11417.000000,11417.000000
mean,1678.584864,2.446440,83.952862,2.555575,5349.813843,644.867199
std,9144.882724,0.931684,67.050650,0.859170,1688.293148,2586.344857
min,300.000000,1.000000,8.440000,1.000000,30.610000,300.000000
25%,1100.000000,2.000000,47.000000,2.000000,4106.280000,495.500000
50%,1276.000000,2.000000,65.000000,2.000000,5083.180000,560.000000
75%,1635.000000,3.000000,97.000000,3.000000,6356.410000,625.000000
max,653400.000000,9.000000,2100.000000,8.000000,10451.660000,217800.000000

In [ ]:
house[house['sqft_per_bhk']>1000]

,location,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
60,other,4395.0,3.0,240.00,3,5460.75,1465.000000
122,Hebbal,5611.5,4.0,477.00,4,8500.40,1402.875000
163,Whitefield,4200.0,4.0,420.00,4,10000.00,1050.000000
248,other,4050.0,3.0,280.00,3,6913.58,1350.000000
259,other,3045.0,3.0,170.00,3,5582.92,1015.000000
...,...,...,...,...,...,...,...
13027,Sarjapur Road,4395.0,4.0,242.00,4,5506.26,1098.750000
13095,other,6652.0,6.0,660.00,4,9921.83,1663.000000
13205,Sarjapur Road,3500.0,3.0,275.00,3,7857.14,1166.666667
13240,Devanahalli,1075.0,2.0,52.57,1,4890.23,1075.000000
13318,Padmanabhanagar,4689.0,4.0,488.00,4,10407.34,1172.250000

In [ ]:

house =house[house['sqft_per_bhk']<1000]
house.describe()

,total_sqft,bath,price,bhk,price_per_sqfeet,sqft_per_bhk
count,11102.000000,11102.000000,11102.000000,11102.000000,11102.000000,11102.000000
mean,1421.031538,2.422086,78.805075,2.540443,5330.252942,561.645866
std,576.721146,0.898612,49.588998,0.839811,1647.444421,111.907986
min,300.000000,1.000000,8.440000,1.000000,500.000000,300.000000
25%,1100.000000,2.000000,47.000000,2.000000,4105.747500,492.500000
50%,1263.000000,2.000000,65.000000,2.000000,5050.510000,555.583333
75%,1600.000000,3.000000,95.000000,3.000000,6307.997500,616.666667
max,6500.000000,9.000000,450.000000,8.000000,10451.660000,997.500000

In [ ]:
house = house.drop(columns=['sqft_per_bhk','price_per_sqfeet'])

In [ ]:
house.head()

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

In [ ]:
Y = house['price']
X=house.drop(columns=['price'])

In [ ]:
X.shape

(11102, 4)

In [ ]:
Y.shape

(11102,)

# model building

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2)

In [ ]:
#applying linear regression

In [ ]:
column_trans =make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [ ]:
scaler = StandardScaler()

In [ ]:
reg = LinearRegression()

In [ ]:
pipe = make_pipeline(column_trans,scaler,reg)

In [ ]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
Y_pred_lr = pipe.predict(X_test)

In [ ]:
r2_score(Y_test,Y_pred_lr)

0.7382036885597724

# Applying lasso

In [ ]:
lasso= Lasso()

In [ ]:
pipe = make_pipeline(column_trans,scaler,lasso)

In [ ]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
Y_pred_lasso=pipe.predict(X_test)
r2_score(Y_test,Y_pred_lasso)

0.7168811263223136

# Applying ridge

```

```

In [ ]:
ridge = Ridge()

In [ ]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [ ]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
Y_pred_ridge = pipe.predict(X_test)
r2_score(Y_test,Y_pred_ridge)

0.7382623537747719

In [ ]:
print('no regularization: ',r2_score(Y_test,Y_pred_lr))
print('lasso: ',r2_score(Y_test,Y_pred_lasso))

print('Ridge: ',r2_score(Y_test,Y_pred_ridge))

no regularization:  0.7382036885597724
lasso:  0.7168811263223136
Ridge:  0.7382623537747719

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('Ridgemodel.pkl','wb'))

In [ ]:
house.to_csv('final_result.csv')